---
- file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  tags:
    - setup

- name: Install nginx
  apt: name={{item}} state=present
  with_items:
    - nginx
    - nginx-extras
  tags:
    - setup

- name: Install Gunicorn
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - gunicorn
  sudo: yes
  tags:
    - setup

- debug:
    msg: "Project Source: {{ hostvars }}"

- debug:
    msg: "Project Source: {{ hostvars[inventory_hostname]['project_src'] }}"

- synchronize:
    src: '{{hostvars[inventory_hostname]["project_src"]}}/'
    dest: /var/www/{{project_name}}-api
    delete: yes
    rsync_opts:
      - "--exclude=*.pyc"
      - "--exclude=__pycache__"
      - "--exclude=settings.py"
  tags:
    - deploy
    - deploy_api

- file:
    path: /var/www/{{project_name}}-api
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  tags:
    - deploy
    - deploy_api

- name: Install API config
  template: src=settings.py dest=/var/www/{{project_name}}-api/settings.py
  tags:
    - setup
    - deploy_api

- pip:
    requirements: /var/www/{{project_name}}-api/requirements.txt
  tags:
    - deploy
    - deploy_api

- name: Install upstart script
  template: src=gunicorn.service dest=/etc/systemd/system/{{project_name}}-api.service
  notify: restart gunicorn
  tags:
    - setup

- name: force restart api
  service: name={{project_name}}-api state=restarted enabled=yes
  tags:
    - deploy
    - deploy_api

- name: Copy admin nginx configuration
  template: src=nginx dest=/etc/nginx/sites-enabled/{{project_name}}-api.conf
  tags:
    - setup

- name: force restart nginx
  service: name=nginx state=restarted enabled=yes
  tags:
    - deploy
    - deploy_api
